# Stage 1: Build React Client
FROM node:14 as client-builder

WORKDIR /app

COPY client/package.json client/package-lock.json ./

RUN npm ci --silent

COPY client ./

RUN npm run build

# Stage 2: Production Client
FROM nginx:latest

WORKDIR /app

COPY --from=client-builder /app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

