# Stage 1: Build Express Server
FROM node:14 as server-builder

WORKDIR /app

COPY server/package.json server/package-lock.json ./

RUN npm ci --silent

COPY server ./

RUN npm run build

# Stage 2: Production Server
FROM node:14-alpine

WORKDIR /app

COPY --from=server-builder /app/package.json ./
COPY --from=server-builder /app/build ./build

RUN npm ci --only=production

EXPOSE 5000

CMD ["npm", "start"]

